### ISSUE TITLE
Changing role name in UI breaks procedure due to role keys not updating

### ISSUE THREAD

**Issue by jamesmontalvo3** [xOPERATIONS/maestro#149]
At present, the method to adjust role names is in a dialog like this:

![image](https://user-images.githubusercontent.com/716482/75818418-72a5d100-5d5e-11ea-96cd-d7757764c0fb.png)

If `crewB` here were changed to `crewC`, this would update the header of the task/activity file and the actor/role info in the procedure file, but the individual callouts for the roles' steps would not be updated. For example:

```yaml
- steps:
  - simo:
      crewB:
        - text: 'Egress Airlock with Crewlock Bag #2; stow on BRT'
        - text: '{{LEFT}} Close thermal cover'
        - text: Check EV1’s config
```

All instances of `crewB` should be changed.
