### ISSUE TITLE
Feature request: Create package/dependency manager

### ISSUE THREAD

**Issue by jamesmontalvo3** [xOPERATIONS/maestro#21]
A package manager à la npm...

A PAT project, like [this one](https://gitlab.com/xOPERATIONS/sts-134) has the following directory structure:

```
build/   <-- this one is generated if you run `pat build`
images/
procedures/
tasks/
```

It would be great to be able to add a `pat.yml` file to the root of PAT projects, which looks something like this:

```yaml
---
name: STS-134 EVA
version: 1.0.12
description: Some description of the procedure
repository:
  type: git
  url: git+https://gitlab.example.com/pat-projects/sts-134.git
dependencies:
  egresses: "^6.10.2"
  ingresses: "^4.3.1"
  get-aheads: "^21.3.3"
```

Then, running `pat install` would retrieve the dependencies `egresses`, `ingresses`, and `get-aheads` at the required versions, and install them under a `packages` directory, e.g.:

```
build/
images/
packages/
  egresses/
  ingresses/
  get-aheads/
procedures/
tasks/
```

Currently, within a procedures file you specify tasks like:

```
tasks:
  - file: sometask.yml
    roles:
      crew: EV1
```

PAT knows to look for `sometask.yml` at `$PROJECT_PATH/tasks/sometask.yml`. With the addition of a package manager it would have to know to also look in `$PROJECT_PATH/packages/*/sometask.yml`. Priority should probably be to look in `tasks/` first, then in `packages/*`. Perhaps to avoid ambiguity the task within the task package should be specified with it's prefix directory, so:

```
tasks:
  - file: egresses/standard.yml
    roles:
      crewA: EV1
      crewB: EV2

  # do some other stuff in here ...

  - file: ingresses/standard.yml
    roles:
      crewA: EV1
      crewB: EV2
```
