### ISSUE TITLE
Feature request: create editable summary timeline with GitLab integration

### ISSUE THREAD

**Issue by jamesmontalvo3** [xOPERATIONS/maestro#37]
Develop a web app that renders a "summary timeline" [1] of a PAT project, and allows reordering, inserting, and deleting tasks. See some example static summary timelines on pages `7-5`, `7-55`, `7-109`, and `7-171` of the [STS-134 EVA checklist](https://www.nasa.gov/centers/johnson/pdf/539922main_EVA_134_F_A.pdf).

Requirements
------------

1. Retrieve PAT project data from a GitLab repository (optional: allow specifying a **base** branch/tag/commit, otherwise just default to `master`). See this [example PAT project](https://gitlab.com/xOPERATIONS/sts-134/).
2. Pick a procedure file from the `./procedures` directory of the PAT project (often there will be one, but there can be many)
3. Render a summary timeline using data both from the procedure file as well as from the task files the procedure file references
4. Allow users to:
   1. Reorder tasks within the timeline
   2. Insert new tasks
   3. Delete existing tasks
3. Allow saving changes back to GitLab, creating a branch from the **base** (optional: open a merge request for the new branch)

Relevant parts of procedure and task files
------------------------------------------

A simple procedure file may look like this:

```yaml
procedure_name: STS-134 EVA 1

columns:

  - key: IV
    actors: "*"
    display: IV/SSRMS

  - key: EV1
    actors: EV1
    display: EV1 (Drew)

  - key: EV3
    actors: EV3
    display: EV3 (Taz)

tasks:

  - file: egress.yml
    roles:
      crewA: EV1
      crewB: EV3

  - file: one-crew-task.yml
    roles:
      crew: EV1

  - file: some-task.yml
    roles:
      crewA: EV3
      crewB: EV1
```

A task file may start like this:

```yaml
title: Some Task

roles:

  - name: crewA
    description: Some description
    duration:
      minutes: 90

  # Note that crewB's duration is 15 minutes shorter, and is offset by 15
  # minutes (i.e. starts 15 minutes later than crewA)
  - name: crewB
    duration:
      hours: 1
      minutes: 15
      offset:
        minutes: 15

steps: 
# steps not shown because they're not relevant to this feature
```

In this example, the procedure defines three tasks:

1. `egress.yml` which both crew member perform
2. `one-crew-task.yml` which just one crew member performs
3. `some-task.yml` which both crew perform

Only the task file for `some-task.yml` is shown. In this, `crewB` is defined as having 15 minutes shorter duration and starting 15 minutes late. The procedure defines `crewB` for this as `EV1`, and to fill that 15 minutes `EV1` is assigned to the `one-crew-task.yml` task before `some-task.yml`.

Note on columns and actors
--------------------------

The column definition from the procedure file above specifies three things:

1. A `key` to uniquely identify the column
2. A `display` that is used as header text at the top of columns in the procedure output
3. A list of `actors` which:
   - On a single-actor column the `actors` and the `key` fields will probably be identical
   - Could be an array of explicitly-listed actors, but most of the time will be a single actor or a *
   - Can have a value of * which means any unspecified actors will get added to this column

The standard EVA output is in three columns, and the current focus of PAT is to get make authoring EVA procedures as awesome as possible. However, other groups are getting interested in this project and will want other output formats. The most likely alternate format is columnless: just a series of steps, probably with just a single actor. We also want to keep it flexible for 2 or 4+ columns. **However, all of those other output formats are not the main focus of this feature request. The primary focus of this feature request is to make EVA editing as good as possible. Maintaining flexibility for future formats is a bonus.**
