### ISSUE TITLE
Feature request: Create a module system

### ISSUE THREAD

**Issue by jamesmontalvo3** [xOPERATIONS/maestro#42]
Currently steps can be added as free-form text like:

```yaml
crewA:
  - step: Configure PGT [B3, CW2] (18.4 ft-lb, 30 RPM, MTL 30.5), 7/16" x 6" wobble

  - step: Install Mounting Bolts in the following order
    checkboxes:
      - "Bolt 1 (port/zenith), ~XX turns Turns: ______ Torque: ______ Light: ______"
      - "Bolt 2 (port/nadir), ~XX turns Turns: ______ Torque: ______ Light: ______"
```

This is manually writing out the text to say to configure the [PGT](https://www.popularmechanics.com/space/a24639/space-drill-used-by-nasa-astronauts/) to a specific torque and seed, then use it to drive some bolts. Developing a module system for PAT could handle commonly used steps. So instead of:

```yaml
- step: Configure PGT [A3, CW2] (18.4 ft-lb, 30 RPM, MTL 30.5), 7/16" x 6" wobble
```

You could do:

```yaml
- PGT: B3, CW2
  socket: 7/16" x 6" wobble
```

And this could generate standard output like this:

![image](https://user-images.githubusercontent.com/716482/65826654-b7c55480-e24e-11e9-86ad-835a2d4b8ccc.png)

### Local modules

To make it easy to add modules without having to directly modify PAT, it would be good to allow them to be added directly to a PAT project. Perhaps in a `modules` directory.
